### ISSUE TITLE
STL aus FreeCAD exportieren

### ISSUE THREAD

**Issue by psi-4ward** [pa-pa/STM32Dimmer#1]
Hi,
könntest du die STLs für das Case aus FreeCAD exportieren und hier einfügen? Ich bekomme hier leider zig Python Errors wenn ich die Datei öffne.

Thxle :)

**Comment by pa-pa** [comment]
Hab ich mal eingecheckt

Am Mo., 27. Sept. 2021 um 14:38 Uhr schrieb Christoph Wiechert <
***@***.***>:

**Comment by psi-4ward** [comment]
Danke ;)
